### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by fluyt02** [fluyt02/GraduationExam#4]
issueを作成いたしました。
ご確認のほどよろしくお願いいたします。

### 実装予定の機能
- [ ] ユーザー関連
  - [ ] 新規登録
  - [ ] ログイン・ログアウト機能
  - [ ] アバター
- [ ] 検索関連
  - [ ] 飲食店の検索機能
    - [ ] キーワード検索
    - [ ] タグ検索 
- [ ] 評価機能
- [ ] お気に入り機能
- [ ] コメント機能
- [ ] Xへのシェア機能
- [ ] googleアカウントでの新規登録

### 必要なページ
- [ ] トップページ(検索)
- [ ] ユーザー関連
  - [ ] 新規登録
  - [ ] ログインページ
  - [ ] 再設定用メールアドレス入力ページ
  - [ ] パスワードリセットページ
- [ ] 検索関連
  - [ ] 検索結果ページ
  - [ ] 検索結果詳細ページ
- [ ] マイページ関連
  - [ ] マイページ 
    - [ ] お気に入り
    - [ ] 評価
  - [ ] プロフィール編集ページ
  - [ ] パスワード変更ページ
- [ ] お問い合わせ
- [ ] 利用規約
- [ ] プライバシーポリシー

**Comment by Tsuchiya2** [comment]
Projectsにアクセスしましたが、看板・issue・ストーリーポイントの確認ができませんでした。
カリキュラムにあるリンク先を参照して上記が閲覧できる状態に対応お願い致します。

<img width="514" alt="スクリーンショット 2024-01-30 12 07 25" src="https://github.com/fluyt02/GraduationExam/assets/61481161/fda1b697-26bb-4307-9ff3-35c116c52a70">

**Comment by fluyt02** [comment]
申し訳ございませんでした
privateからpublicに変更いたしました
ご確認のほどよろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
確認できました。対応ありがとうございます。
以下コメントになります。

---

ストーリーポイント5が付いているissueはもう少し分解しましょう。

```
# 例
- ヘッダー作成 1
- フッター作成 1
- アプリの使い方説明 2
```

**Comment by fluyt02** [comment]
ご確認いただきありがとうございます
一部変更いたしました
再度ご確認のほどよろしくお願いいたします

**Comment by Tsuchiya2** [comment]
フロントエンド及びバックエンド用のフォルダ作成とありますが、これは何をするのでしょうか？

フロント関連言語の調査・検証にはtailwindcssの調査とあるのは確認できたのですが、React等のJavaScriptフレームワークを使うということでしょうか？READMEにはそのように書かれておらず、分ける必要がないかと思いますが。

**Comment by fluyt02** [comment]
ご確認いただきありがとうございます
フロントエンド及びバックエンド用のフォルダ作成は、他の方がフロントエンド用のフォルダとバックエンド用のフォルダを分けて環境構築をしていたのを参考に記述しました。

関連言語の調査に関しては、現時点で扱うフレームワークを決めておらず、検証に合わせてREADMEを修正しようと考えていました。
cssはtailwindcssを考えており、javascriptはreact等を考えております。

フロント関連言語の調査・検証にReactの調査を追記しました。

再度ご確認のほどよろしくお願いいたします。

**Comment by busitora** [comment]
LGTMです！

**Comment by fluyt02** [comment]
ありがとうございました
closeさせていただきます。
